service: my-express-application

plugins:
  - serverless-offline #serverless-offline needs to be last in the list
  - serverless-dynamodb-local

custom:
  tableName: 'metas-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["MetasDynamoDBTable", "Arn" ] }
  environment:
    METAS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getMeta:
    handler: index.handler
    events:
      - http: 'GET /metas/{proxy+}'
  createMeta:
    handler: index.handler
    events:
      - http: 'POST /metas'

resources:
  Resources:
    MetasDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: metaId
            AttributeType: S
        KeySchema:
          -
            AttributeName: metaId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}